### ISSUE TITLE
Banner: Banner overlay is in the center now, it should be at left side (ViewPort: 980px, 640px,320px | All devices | All browsers) 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Mandhura-Communications#20]
![2016-05-11_1458](https://cloud.githubusercontent.com/assets/13309806/15176581/690df6f0-1789-11e6-8a3f-cf6cb9d61e54.png)

**Comment by nakul-titan** [comment]
if we left aligned the overlay section, it will overlap with the arrows.

**Comment by nakul-titan** [comment]
Banner content will overlap with the arows and we decrease the font size to small extent, so it was made hidden in those ports.
