### ISSUE TITLE
Banner: Overlay shouldn't be seperated from the banner (Viewport: 640px,360px | Samsung, iPod | All browsers)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Mandhura-Communications#23]
![2016-05-10_1734](https://cloud.githubusercontent.com/assets/13309806/15177714/25844ac8-178f-11e6-9189-08a99ae754e8.png)

**Comment by nakul-titan** [comment]
in small devices, we wont be able to see the banner image, thats why overlay was seperated from the banner
