### ISSUE TITLE
Home: Our Recent Projects - Lacking of slick navigation arrows in Samsung,iPod,iPad,iPad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Mandhura-Communications#33]
![2016-05-11_1639](https://cloud.githubusercontent.com/assets/13309806/15179045/07c3c092-1797-11e6-96a7-35474b114e65.png)

**Comment by nakul-titan** [comment]
it was intentionally hided, due to overlapping with the images
