### ISSUE TITLE
Search Page: It should be implemented as like given design

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Mandhura-Communications#47]
![2016-05-12_1017](https://cloud.githubusercontent.com/assets/13309806/15204431/eeadce1a-182a-11e6-88fa-7346cdcf7759.png)

**Comment by roseliesromeo** [comment]
Please refer to this page for similar implementation.
http://skyhook-imp.stage.titanweb.com.au/index.php?s=&searchsubmit=
