### ISSUE TITLE
Banner: Video button will display even if button label field is empty.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Mandhura-Communications#70]
![image](https://cloud.githubusercontent.com/assets/11186313/15733005/58e5974c-28b4-11e6-8b82-e5fd5d8d76de.png)

**Comment by nakul-titan** [comment]
This field has been changed to Video link as per scope. 
I request you to please re-check again.

**Comment by roseliesromeo** [comment]
I believe this is wrong since most of the sites, video link will be from business details.  But if there has to be another field for the video link, there must be field for the video button label for it to be dynamic.

**Comment by roseliesromeo** [comment]
There is still no "Watch our video" button label acf field.
